name: Terraform CI/CD - Destroy Network Layer
on:
  workflow_dispatch:
    inputs:
      confirm-destroy:
        description: 'Type "DESTROY" to confirm'
        required: true
        type: string

      environment:
        description: 'Environment to destroy (stream or main)'
        required: true
        type: choice
        options:
          - stream
          - main

env:
  AWS_REGION: 'us-east-1'

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
    - name: Validate confirmation
      if: ${{ github.event.inputs['confirm-destroy'] != 'DESTROY' }}
      run: |
        echo "Destroy confirmation not provided. Exiting."
        exit 1

    - name: Select tfvars file
      run: |
        if [[ "${{ github.event.inputs.environment }}" == "main" ]]; then
          echo "TFVARS_FILE=main.tfvars" >> $GITHUB_ENV
        else
          echo "TFVARS_FILE=stream.tfvars" >> $GITHUB_ENV
        fi

    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: ./StockWiz/ECS-Layer
      run: terraform init

    - name: Terraform Destroy
      working-directory: ./StockWiz/ECS-Layer
      run: terraform destroy -auto-approve --var-file=main.tfvars
    
    - name: Cleanup Complete
      run: echo "Network Layer resources destroyed successfully."
      
